# Generated by Django 3.2.7 on 2021-09-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('nome', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=100)),
                ('cpf', models.IntegerField()),
                ('telefone', models.IntegerField()),
                ('endereço', models.CharField(max_length=250)),
                ('data_nascimento', models.DateField()),
                ('status_civil', models.CharField(max_length=250)),
                ('salario', models.IntegerField()),
            ],
        ),
    ]
