# Generated by Django 3.2.7 on 2021-09-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210906_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
