
# Generated by Django 3.2.7 on 2021-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_cliente_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='salario',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
