# Generated by Django 3.2.7 on 2021-09-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cliente_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='salario',
            field=models.DecimalField(max_digits=5,decimal_places=2)
        ),
    ]
